"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, CheckCircle2, Copy, Shield, ShieldOff, UserCheck, Users } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { authFetch } from "@/lib/auth";

type AdminUser = { id: string; email: string; display_name: string | null; status: string; role_codes: string[]; created_at: string };
type Role = { id: string; code: string; name: string; description: string | null; is_system: boolean; permission_codes: string[] };
type Permission = { code: string; name: string; description: string; domain: string };
type Audit = { id: string; action: string; actor_email: string | null; target_user_id: string | null; created_at: string; detail: Record<string, unknown> | null };

const api = {
  users: () => authFetch<AdminUser[]>("/api/iam/admin/users"),
  roles: () => authFetch<Role[]>("/api/iam/admin/roles"),
  permissions: () => authFetch<Permission[]>("/api/iam/admin/permissions"),
  audit: () => authFetch<Audit[]>("/api/iam/admin/audit-events?limit=100"),
  mutate: (path: string, method: string, body?: unknown) => authFetch(`/api/iam/admin${path}`, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }),
};

export default function AdminPage() {
  const queryClient = useQueryClient(); const [tab, setTab] = useState<"users" | "roles" | "audit">("users"); const [notice, setNotice] = useState("");
  const users = useQuery({ queryKey: ["admin-users"], queryFn: api.users });
  const roles = useQuery({ queryKey: ["admin-roles"], queryFn: api.roles });
  const permissions = useQuery({ queryKey: ["admin-permissions"], queryFn: api.permissions });
  const audit = useQuery({ queryKey: ["admin-audit"], queryFn: api.audit, enabled: tab === "audit" });
  const action = useMutation({ mutationFn: ({ path, method, body }: { path: string; method: string; body?: unknown }) => api.mutate(path, method, body), onSuccess: async () => { setNotice("变更已保存并写入审计日志。"); await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin-users"] }), queryClient.invalidateQueries({ queryKey: ["admin-roles"] }), queryClient.invalidateQueries({ queryKey: ["admin-audit"] })]); }, onError: (error) => setNotice(error.message) });
  async function createRole(form: FormData) { const selected = permissions.data?.filter((permission) => form.get(permission.code) === "on").map((permission) => permission.code) ?? []; action.mutate({ path: "/roles", method: "POST", body: { code: form.get("code"), name: form.get("name"), description: form.get("description"), permission_codes: selected } }); }
  return <AppShell><div className="page admin-page"><header className="page-header"><div><span className="eyebrow">IAM / CONTROL PLANE</span><h1>身份与权限管理</h1><p>管理身份、角色与固定权限目录。管理员权限不会赋予读取其他用户研究内容的能力。</p></div><Shield size={36} color="var(--cyan)" /></header><nav className="admin-tabs" aria-label="管理模块"><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}><Users size={15} /> 用户</button><button className={tab === "roles" ? "active" : ""} onClick={() => setTab("roles")}><Shield size={15} /> 角色</button><button className={tab === "audit" ? "active" : ""} onClick={() => setTab("audit")}><Activity size={15} /> 审计</button></nav>{notice && <p className="form-alert admin-notice">{notice}</p>}
    {tab === "users" && <section className="admin-user-list">{users.data?.map((user) => <article className="panel admin-user" key={user.id}><div className="admin-user-main"><span className={`status-chip status-${user.status}`}>{user.status}</span><h2>{user.display_name || user.email}</h2><p>{user.email}</p><div className="role-chips">{user.role_codes.map((role) => <i key={role}>{role}</i>)}</div></div><div className="admin-user-meta"><span className="mono">{user.id}</span><small>创建于 {new Date(user.created_at).toLocaleDateString()}</small></div><div className="admin-user-actions">{user.status === "pending_approval" && <button className="primary" onClick={() => action.mutate({ path: `/users/${user.id}/approve`, method: "POST", body: { role_codes: ["researcher"] } })}><UserCheck size={14} /> 批准为研究员</button>}{user.status === "disabled" ? <button className="secondary" onClick={() => action.mutate({ path: `/users/${user.id}/enable`, method: "POST" })}><CheckCircle2 size={14} /> 启用</button> : <button className="danger" onClick={() => action.mutate({ path: `/users/${user.id}/disable`, method: "POST" })}><ShieldOff size={14} /> 禁用</button>}<select aria-label="角色" value={user.role_codes[0] ?? ""} onChange={(event) => action.mutate({ path: `/users/${user.id}/roles`, method: "PUT", body: { role_codes: [event.target.value] } })}><option value="">无角色</option>{roles.data?.map((role) => <option key={role.code} value={role.code}>{role.name}</option>)}</select></div></article>)}</section>}
    {tab === "roles" && <div className="admin-role-grid"><section className="panel"><div className="panel-header"><h2>角色目录</h2></div><div className="role-list">{roles.data?.map((role) => <article key={role.id}><div><b>{role.name}</b><span className="mono">{role.code} · {role.is_system ? "SYSTEM" : "CUSTOM"}</span></div><p>{role.description}</p><div className="permission-mini">{role.permission_codes.map((code) => <i key={code}>{code}</i>)}</div>{!role.is_system && <button className="danger" onClick={() => action.mutate({ path: `/roles/${role.id}`, method: "DELETE" })}>删除</button>}{role.is_system && <button className="secondary" onClick={() => action.mutate({ path: `/roles/${role.id}/copy`, method: "POST", body: { new_code: `${role.code}_copy_${Date.now().toString().slice(-4)}`, new_name: `${role.name} Copy` } })}><Copy size={13} /> 复制</button>}</article>)}</div></section><section className="panel"><div className="panel-header"><h2>组合自定义角色</h2></div><form action={createRole} className="panel-body auth-form"><div className="field"><label htmlFor="role-code">稳定代码</label><input id="role-code" name="code" required pattern="[a-z0-9_.-]+" /></div><div className="field"><label htmlFor="role-name">显示名称</label><input id="role-name" name="name" required /></div><div className="field"><label htmlFor="role-description">说明</label><textarea id="role-description" name="description" /></div><div className="permission-catalog">{Object.entries(Object.groupBy(permissions.data ?? [], (permission) => permission.domain)).map(([domain, items]) => <fieldset key={domain}><legend>{domain}</legend>{items?.map((permission) => <label key={permission.code}><input type="checkbox" name={permission.code} /><span><b>{permission.name}</b><small>{permission.code}</small></span></label>)}</fieldset>)}</div><button className="primary">创建角色</button></form></section></div>}
    {tab === "audit" && <section className="panel"><div className="panel-header"><h2>最近 100 条 IAM 审计事件</h2></div><div className="audit-table" role="table">{audit.data?.map((event) => <article role="row" key={event.id}><time>{new Date(event.created_at).toLocaleString()}</time><b>{event.action}</b><span>{event.actor_email || "SYSTEM"}</span><code>{event.target_user_id || "—"}</code></article>)}</div></section>}
  </div></AppShell>;
}
